# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - o-susie

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://adrienazure.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f867a5142bb94503bba3d0e1a5d2825c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_12dcccfa517143a8937e0f84b69ceb3c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: adrienazure.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f867a5142bb94503bba3d0e1a5d2825c }}/o-susie:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'o-susie'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e26af89cc8304d2685565c9ec098666d }}
        images: 'adrienazure.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f867a5142bb94503bba3d0e1a5d2825c }}/o-susie:${{ github.sha }}'